turtlebot2: #namespace

    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #qlearn parameters
    alpha: 0.8
    gamma: 0.9
    epsilon: 0.99
    epsilon_discount: 0.999
    nepisodes: 15000
    nsteps: 300

    running_step: 0.06 # Time for each step
    wait_time: 0.1 # Time to wait in the reset phases

    n_actions: 3 # We have 5 actions, Forward, Stop, turn left, turn right, backward

    num_of_sector: 36

    speed_step: 1.0 # Time to wait in the reset phases
    
    obstacle_pose_radius: 3
    
    velocity:
        linear:
            x: 1.5
            y: 0.0
            z: 0.0
        angular:
            x: 0.0 
            y: 0.0
            z: 0.3
    
    robot_movement_area:
        min: {x: -6.0, y: -6.0}
        max: {x: 6.0, y: 6.0}

    goal_point:
        x: 6.0
        y: 0.0
        z: 0.0

    # you should define as many reward as number of sensitivity. These must be a increasing number.
    sensitiviy_distances:
        - 10
        - 6
        - 4
        - 2
        - 1
        - 0.4
        - 0.2
        - 0.01
        # ...
    
    area_violation_reward: -70
    goal_reached_reward: 300
    collsion_detected_reward: -100